apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fsx-sc
provisioner: fsx.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-claim
  namespace: llm-training
spec:
  storageClassName: fsx-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti